import React from 'react';
import type { Metadata } from 'next';

import '../global-styles/main.scss';
import { mainFont, headingFont } from '../global-styles/fonts';

export const metadata: Metadata = {
    title: 'Explore BG',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${mainFont.variable} ${headingFont.variable}`}>
            <body>{children}</body>
        </html>
    );
}
